services:
  keycap_playground_web:
    container_name: keycap_playground_web
    build:
      context: .
    volumes:
      - ./generated:/app/generated
      - ./templates:/app/templates

  viewer:
    container_name: keycap_playground_viewer
    build:
      context: ./viewer
    ports:
      - "5173:5173"
    depends_on:
      - keycap_playground_web